# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/login.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/login.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\n\tcom.protoB\005Login'),
  serialized_pb=_b('\n\x11proto/login.proto\"9\n\x08LoginReq\x12\x0f\n\x07\x61\x63\x63ount\x18\x01 \x01(\t\x12\x0b\n\x03pwd\x18\x02 \x01(\t\x12\x0f\n\x07\x63onn_id\x18\x03 \x01(\x05\"\x1c\n\x08LoginRsp\x12\x10\n\x08\x65rr_code\x18\x01 \x01(\x05\"/\n\t_RoleInfo\x12\x0f\n\x07role_id\x18\x01 \x01(\x05\x12\x11\n\trole_name\x18\x02 \x01(\t\"S\n\x0fLoadRoleListRsp\x12\x0f\n\x07\x61\x63\x63ount\x18\x01 \x01(\t\x12\x10\n\x08\x65rr_code\x18\x02 \x01(\x05\x12\x1d\n\trole_list\x18\x03 \x03(\x0b\x32\n._RoleInfo\"3\n\rCreateRoleReq\x12\x0f\n\x07\x61\x63\x63ount\x18\x01 \x01(\t\x12\x11\n\trole_name\x18\x02 \x01(\t\"@\n\rCreateRoleRsp\x12\x10\n\x08\x65rr_code\x18\x01 \x01(\x05\x12\x1d\n\trole_info\x18\x02 \x01(\x0b\x32\n._RoleInfo\"-\n\tEnterGame\x12\x0f\n\x07role_id\x18\x01 \x01(\x05\x12\x0f\n\x07\x61\x63\x63ount\x18\x02 \x01(\t\"?\n\x0c\x45nterGameRsp\x12\x10\n\x08\x65rr_code\x18\x01 \x01(\x05\x12\x1d\n\trole_info\x18\x02 \x01(\x0b\x32\n._RoleInfo\"\x0f\n\rDisconnectReq\"\x1f\n\rDisconnectRsp\x12\x0e\n\x06reason\x18\x01 \x01(\t\")\n\x08StartKcp\x12\x0e\n\x06kcp_id\x18\x01 \x01(\x05\x12\r\n\x05token\x18\x02 \x01(\tB\x12\n\tcom.protoB\x05Loginb\x06proto3')
)




_LOGINREQ = _descriptor.Descriptor(
  name='LoginReq',
  full_name='LoginReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='account', full_name='LoginReq.account', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pwd', full_name='LoginReq.pwd', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='conn_id', full_name='LoginReq.conn_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=78,
)


_LOGINRSP = _descriptor.Descriptor(
  name='LoginRsp',
  full_name='LoginRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='err_code', full_name='LoginRsp.err_code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=108,
)


__ROLEINFO = _descriptor.Descriptor(
  name='_RoleInfo',
  full_name='_RoleInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='role_id', full_name='_RoleInfo.role_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='role_name', full_name='_RoleInfo.role_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=157,
)


_LOADROLELISTRSP = _descriptor.Descriptor(
  name='LoadRoleListRsp',
  full_name='LoadRoleListRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='account', full_name='LoadRoleListRsp.account', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='err_code', full_name='LoadRoleListRsp.err_code', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='role_list', full_name='LoadRoleListRsp.role_list', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=159,
  serialized_end=242,
)


_CREATEROLEREQ = _descriptor.Descriptor(
  name='CreateRoleReq',
  full_name='CreateRoleReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='account', full_name='CreateRoleReq.account', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='role_name', full_name='CreateRoleReq.role_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=244,
  serialized_end=295,
)


_CREATEROLERSP = _descriptor.Descriptor(
  name='CreateRoleRsp',
  full_name='CreateRoleRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='err_code', full_name='CreateRoleRsp.err_code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='role_info', full_name='CreateRoleRsp.role_info', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=297,
  serialized_end=361,
)


_ENTERGAME = _descriptor.Descriptor(
  name='EnterGame',
  full_name='EnterGame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='role_id', full_name='EnterGame.role_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='account', full_name='EnterGame.account', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=363,
  serialized_end=408,
)


_ENTERGAMERSP = _descriptor.Descriptor(
  name='EnterGameRsp',
  full_name='EnterGameRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='err_code', full_name='EnterGameRsp.err_code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='role_info', full_name='EnterGameRsp.role_info', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=410,
  serialized_end=473,
)


_DISCONNECTREQ = _descriptor.Descriptor(
  name='DisconnectReq',
  full_name='DisconnectReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=475,
  serialized_end=490,
)


_DISCONNECTRSP = _descriptor.Descriptor(
  name='DisconnectRsp',
  full_name='DisconnectRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reason', full_name='DisconnectRsp.reason', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=492,
  serialized_end=523,
)


_STARTKCP = _descriptor.Descriptor(
  name='StartKcp',
  full_name='StartKcp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='kcp_id', full_name='StartKcp.kcp_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='token', full_name='StartKcp.token', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=525,
  serialized_end=566,
)

_LOADROLELISTRSP.fields_by_name['role_list'].message_type = __ROLEINFO
_CREATEROLERSP.fields_by_name['role_info'].message_type = __ROLEINFO
_ENTERGAMERSP.fields_by_name['role_info'].message_type = __ROLEINFO
DESCRIPTOR.message_types_by_name['LoginReq'] = _LOGINREQ
DESCRIPTOR.message_types_by_name['LoginRsp'] = _LOGINRSP
DESCRIPTOR.message_types_by_name['_RoleInfo'] = __ROLEINFO
DESCRIPTOR.message_types_by_name['LoadRoleListRsp'] = _LOADROLELISTRSP
DESCRIPTOR.message_types_by_name['CreateRoleReq'] = _CREATEROLEREQ
DESCRIPTOR.message_types_by_name['CreateRoleRsp'] = _CREATEROLERSP
DESCRIPTOR.message_types_by_name['EnterGame'] = _ENTERGAME
DESCRIPTOR.message_types_by_name['EnterGameRsp'] = _ENTERGAMERSP
DESCRIPTOR.message_types_by_name['DisconnectReq'] = _DISCONNECTREQ
DESCRIPTOR.message_types_by_name['DisconnectRsp'] = _DISCONNECTRSP
DESCRIPTOR.message_types_by_name['StartKcp'] = _STARTKCP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LoginReq = _reflection.GeneratedProtocolMessageType('LoginReq', (_message.Message,), {
  'DESCRIPTOR' : _LOGINREQ,
  '__module__' : 'proto.login_pb2'
  # @@protoc_insertion_point(class_scope:LoginReq)
  })
_sym_db.RegisterMessage(LoginReq)

LoginRsp = _reflection.GeneratedProtocolMessageType('LoginRsp', (_message.Message,), {
  'DESCRIPTOR' : _LOGINRSP,
  '__module__' : 'proto.login_pb2'
  # @@protoc_insertion_point(class_scope:LoginRsp)
  })
_sym_db.RegisterMessage(LoginRsp)

_RoleInfo = _reflection.GeneratedProtocolMessageType('_RoleInfo', (_message.Message,), {
  'DESCRIPTOR' : __ROLEINFO,
  '__module__' : 'proto.login_pb2'
  # @@protoc_insertion_point(class_scope:_RoleInfo)
  })
_sym_db.RegisterMessage(_RoleInfo)

LoadRoleListRsp = _reflection.GeneratedProtocolMessageType('LoadRoleListRsp', (_message.Message,), {
  'DESCRIPTOR' : _LOADROLELISTRSP,
  '__module__' : 'proto.login_pb2'
  # @@protoc_insertion_point(class_scope:LoadRoleListRsp)
  })
_sym_db.RegisterMessage(LoadRoleListRsp)

CreateRoleReq = _reflection.GeneratedProtocolMessageType('CreateRoleReq', (_message.Message,), {
  'DESCRIPTOR' : _CREATEROLEREQ,
  '__module__' : 'proto.login_pb2'
  # @@protoc_insertion_point(class_scope:CreateRoleReq)
  })
_sym_db.RegisterMessage(CreateRoleReq)

CreateRoleRsp = _reflection.GeneratedProtocolMessageType('CreateRoleRsp', (_message.Message,), {
  'DESCRIPTOR' : _CREATEROLERSP,
  '__module__' : 'proto.login_pb2'
  # @@protoc_insertion_point(class_scope:CreateRoleRsp)
  })
_sym_db.RegisterMessage(CreateRoleRsp)

EnterGame = _reflection.GeneratedProtocolMessageType('EnterGame', (_message.Message,), {
  'DESCRIPTOR' : _ENTERGAME,
  '__module__' : 'proto.login_pb2'
  # @@protoc_insertion_point(class_scope:EnterGame)
  })
_sym_db.RegisterMessage(EnterGame)

EnterGameRsp = _reflection.GeneratedProtocolMessageType('EnterGameRsp', (_message.Message,), {
  'DESCRIPTOR' : _ENTERGAMERSP,
  '__module__' : 'proto.login_pb2'
  # @@protoc_insertion_point(class_scope:EnterGameRsp)
  })
_sym_db.RegisterMessage(EnterGameRsp)

DisconnectReq = _reflection.GeneratedProtocolMessageType('DisconnectReq', (_message.Message,), {
  'DESCRIPTOR' : _DISCONNECTREQ,
  '__module__' : 'proto.login_pb2'
  # @@protoc_insertion_point(class_scope:DisconnectReq)
  })
_sym_db.RegisterMessage(DisconnectReq)

DisconnectRsp = _reflection.GeneratedProtocolMessageType('DisconnectRsp', (_message.Message,), {
  'DESCRIPTOR' : _DISCONNECTRSP,
  '__module__' : 'proto.login_pb2'
  # @@protoc_insertion_point(class_scope:DisconnectRsp)
  })
_sym_db.RegisterMessage(DisconnectRsp)

StartKcp = _reflection.GeneratedProtocolMessageType('StartKcp', (_message.Message,), {
  'DESCRIPTOR' : _STARTKCP,
  '__module__' : 'proto.login_pb2'
  # @@protoc_insertion_point(class_scope:StartKcp)
  })
_sym_db.RegisterMessage(StartKcp)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
