# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/server_only/login_srv.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import login_pb2 as proto_dot_login__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/server_only/login_srv.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n!proto/server_only/login_srv.proto\x1a\x11proto/login.proto\"\"\n\x0fLoadRoleListReq\x12\x0f\n\x07\x61\x63\x63ount\x18\x01 \x01(\t\"/\n\x0bLoadRoleReq\x12\x0f\n\x07role_id\x18\x01 \x01(\x05\x12\x0f\n\x07\x63onn_id\x18\x02 \x01(\x05\"<\n\x0bLoadRoleRsp\x12\x0f\n\x07\x63onn_id\x18\x01 \x01(\x05\x12\x1c\n\trole_info\x18\x02 \x01(\x0b\x32\t.RoleInfob\x06proto3')
  ,
  dependencies=[proto_dot_login__pb2.DESCRIPTOR,])




_LOADROLELISTREQ = _descriptor.Descriptor(
  name='LoadRoleListReq',
  full_name='LoadRoleListReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='account', full_name='LoadRoleListReq.account', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=90,
)


_LOADROLEREQ = _descriptor.Descriptor(
  name='LoadRoleReq',
  full_name='LoadRoleReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='role_id', full_name='LoadRoleReq.role_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='conn_id', full_name='LoadRoleReq.conn_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=139,
)


_LOADROLERSP = _descriptor.Descriptor(
  name='LoadRoleRsp',
  full_name='LoadRoleRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='conn_id', full_name='LoadRoleRsp.conn_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='role_info', full_name='LoadRoleRsp.role_info', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=201,
)

_LOADROLERSP.fields_by_name['role_info'].message_type = proto_dot_login__pb2._ROLEINFO
DESCRIPTOR.message_types_by_name['LoadRoleListReq'] = _LOADROLELISTREQ
DESCRIPTOR.message_types_by_name['LoadRoleReq'] = _LOADROLEREQ
DESCRIPTOR.message_types_by_name['LoadRoleRsp'] = _LOADROLERSP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LoadRoleListReq = _reflection.GeneratedProtocolMessageType('LoadRoleListReq', (_message.Message,), {
  'DESCRIPTOR' : _LOADROLELISTREQ,
  '__module__' : 'proto.server_only.login_srv_pb2'
  # @@protoc_insertion_point(class_scope:LoadRoleListReq)
  })
_sym_db.RegisterMessage(LoadRoleListReq)

LoadRoleReq = _reflection.GeneratedProtocolMessageType('LoadRoleReq', (_message.Message,), {
  'DESCRIPTOR' : _LOADROLEREQ,
  '__module__' : 'proto.server_only.login_srv_pb2'
  # @@protoc_insertion_point(class_scope:LoadRoleReq)
  })
_sym_db.RegisterMessage(LoadRoleReq)

LoadRoleRsp = _reflection.GeneratedProtocolMessageType('LoadRoleRsp', (_message.Message,), {
  'DESCRIPTOR' : _LOADROLERSP,
  '__module__' : 'proto.server_only.login_srv_pb2'
  # @@protoc_insertion_point(class_scope:LoadRoleRsp)
  })
_sym_db.RegisterMessage(LoadRoleRsp)


# @@protoc_insertion_point(module_scope)
