
// Generated by the make proto tool

#include "proto.h"

std::shared_ptr<google::protobuf::Message> CreateMsgById(int msgId)
{
	switch (msgId)
	{
		case MSG_ID_LOGIN:
		return std::shared_ptr<google::protobuf::Message>(new Login());
		case MSG_ID_LOGINRSP:
		return std::shared_ptr<google::protobuf::Message>(new LoginRsp());
		case MSG_ID_TEST:
		return std::shared_ptr<google::protobuf::Message>(new Test());
	}
	return NULL;
}