
// Generated by tool.  DO NOT EDIT!

#pragma once

#include "proto/server_only/login_srv.pb.h"
#include "proto/login.pb.h"
#include "proto/scene.pb.h"
#include "proto/role.pb.h"
#include "proto/server_only/common.pb.h"
#include "proto/test.pb.h"

#ifdef PROTO_BUFFER_EXPORT
#ifndef PROTO_BUFFER_API
#define PROTO_BUFFER_API __declspec(dllexport)
#endif
#else
#define PROTO_BUFFER_API
#endif

enum PROTO_MSG_ID {
	MSG_ID_CLIENT_DISCONNECT = 1,
	MSG_ID_CREATE_ROLE_REQ = 2,
	MSG_ID_CREATE_ROLE_RSP = 3,
	MSG_ID_DISCONNECT_REQ = 4,
	MSG_ID_DISCONNECT_RSP = 5,
	MSG_ID_ENTER_GAME = 6,
	MSG_ID_ENTER_GAME_RSP = 7,
	MSG_ID_ENTER_SCENE_REQ = 8,
	MSG_ID_ENTER_SCENE_RSP = 9,
	MSG_ID_GM_CMD = 10,
	MSG_ID_GM_CMD_RSP = 11,
	MSG_ID_LOAD_ROLE_LIST_RSP = 12,
	MSG_ID_LOGIN_REQ = 13,
	MSG_ID_LOGIN_RSP = 14,
	MSG_ID_RPC_MSG = 15,
	MSG_ID_RPC_MSG_RSP = 16,
	MSG_ID_TEST_REQ = 17,
	
};

typedef PROTO_MSG_ID MSG_ID;

PROTO_BUFFER_API std::shared_ptr<google::protobuf::Message> CreateMsgById(int msgId);