
// Generated by tool.  DO NOT EDIT!

#pragma once

{% for file_name in render_obj.proto_files %}
#include "proto/{{ file_name }}.pb.h"
{% endfor %}

#ifdef PROTO_BUFFER_EXPORT
#ifndef PROTO_BUFFER_API
#define PROTO_BUFFER_API __declspec(dllexport)
#endif
#else
#define PROTO_BUFFER_API
#endif

enum PROTO_MSG_ID {
{% for proto_obj in render_obj.proto_list %}
	{{ proto_obj.msg_id_var }} = {{ proto_obj.msg_id }},
{% endfor %}	
};

typedef PROTO_MSG_ID MSG_ID;

PROTO_BUFFER_API std::shared_ptr<google::protobuf::Message> CreateMsgById(int msgId);
PROTO_BUFFER_API std::shared_ptr<google::protobuf::Message> createMessage(int msgId, char* data, int dataLen);
